apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeconfig-monitor
  namespace: tools-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubeconfig-monitor
  template:
    metadata:
      labels:
        app: kubeconfig-monitor
    spec:
      # 初始化容器
      initContainers:
        - name: kubeconfig-fetcher
          image: kubeconfig-fetcher:1.0
          imagePullPolicy: Always
          env:
            - name: RANCHER_SERVER
              value: ""
            - name: RANCHER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: rancher-api-credentials
                  key: token
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: kubeconfig-shared
              mountPath: /data
      # 主应用容器
      containers:
        - name: pod-rollback
          image: pod-rollback:1.0
          imagePullPolicy: Always
          env:
            - name: MONITOR_NAMESPACE
              value: "tools-dev"
            - name: KUBECONFIG_PATH
              value: ""
            - name: TIME_WINDOW
              value: "5m"
            - name: THRESHOLD
              value: "3"
            - name: NOTIFY_TYPE
              value: "wechat"
            - name: WEBHOOK
              value: ""
            - name: ROLLBACK
              value: "true"
          volumeMounts:
            - name: kubeconfig-shared
              mountPath: /app-config/kubeconfig.yaml
              subPath: kubeconfig.yaml
      imagePullSecrets:
        - name: default-secret
      volumes:
        - name: kubeconfig-shared
          emptyDir:
            medium: Memory
            sizeLimit: 1Mi
---
apiVersion: v1
kind: Secret
metadata:
  name: rancher-api-credentials
  namespace: tools-dev
data:
  token: base64(base64(rancher-token))
